### ISSUE TITLE
Bom and/or readme doesn't include the gals etc.

### ISSUE THREAD

**Issue by ogg1e** [wiretap-retro/Prelude-ZII-Sound-Card#1]
This is great. Thanks so much for doing this. But the bom and readme don't specify the gals that needed, or the plcc chip either.

**Comment by wiretap-retro** [comment]
Not sure why you're not seeing it. The GALs and PLCC chips are specified in the HTML BOMs, and the GAL code is in the logic folder.

**Comment by ogg1e** [comment]
Sorry. I meant the xls spreadsheet. :-)

**Comment by wiretap-retro** [comment]
That's for Mouser only. They don't stock old parts that need sourced from elsewhere or harvested from old parts.
