### ISSUE TITLE
mouser cart and bom have differences

### ISSUE THREAD

**Issue by ogg1e** [wiretap-retro/Prelude-ZII-Sound-Card#2]
the schematic and bom for r1 is 2R, but the mouser cart xls shows 1.6R

The schematic and bom also show 1000pf for c47 & c48, but they're absent from the spreadsheet.

**Comment by wiretap-retro** [comment]
1.6R is acceptable, as there isn't an easily accessible part available in 2 ohm that would fit. I've updated the spreadsheet to include the C47 and C48 with the right part.
